const actionTypes = {
   RECEIVE_CIRCLES: 'RECEIVE_CIRCLES',
   RECEIVE_SINGLE_POSTS: 'RECEIVE_SINGLE_POSTS',
   JOIN_CIRCLE: 'JOIN_CIRCLE',
   PUBLISH_NEW_POST: 'PUBLISH_NEW_POST'
}

module.exports = actionTypes