const actionTypes = {
   RECEIVE_CIRCLES: 'RECEIVE_CIRCLES',
   RECEIVE_SINGLE_POSTS: 'RECEIVE_SINGLE_POSTS',
   RECEIVE_SOLE_POST: 'RECEIVE_SOLE_POST',
   ADD_SINGLE_POSTS: 'ADD_SINGLE_POSTS',
   JOIN_CIRCLE: 'JOIN_CIRCLE',
   PUBLISH_NEW_POST: 'PUBLISH_NEW_POST',
   LIKE_ACTION: 'LIKE_ACTION',
   COLLECT_ACTION: 'COLLECT_ACTION'
}

module.exports = actionTypes