const actionTypes = {
  RECEIVE_CIRCLES: 'RECEIVE_CIRCLES',
  RECEIVE_SOLE_CIRCLE: 'RECEIVE_SOLE_CIRCLE',
  RECEIVE_POPULAR_POSTS: 'RECEIVE_POPULAR_POSTS',
  ADD_POPULAR_POSTS: 'ADD_POPULAR_POSTS',
  RECEIVE_SINGLE_POSTS: 'RECEIVE_SINGLE_POSTS',
  ADD_SINGLE_POSTS: 'ADD_SINGLE_POSTS',
  JOIN_CIRCLE: 'JOIN_CIRCLE',
  PUBLISH_NEW_POST: 'PUBLISH_NEW_POST',
  RECEIVE_SOLE_POST: 'RECEIVE_SOLE_POST',
  LIKE_ACTION: 'LIKE_ACTION',
  COLLECT_ACTION: 'COLLECT_ACTION',
  RECEIVE_JOINED_CIRCLES: 'RECEIVE_JOINED_CIRCLES',
  RECEIVE_MINE_POSTS: 'RECEIVE_MINE_POSTS',
  ADD_MINE_POSTS: 'ADD_MINE_POSTS',
  RECEIVE_LIKED_POSTS: 'RECEIVE_LIKED_POSTS',
  ADD_LIKED_POSTS: 'ADD_LIKED_POSTS',
  RECEIVE_COLLECTED_POSTS: 'RECEIVE_COLLECTED_POSTS',
  ADD_COLLECTED_POSTS: 'ADD_COLLECTED_POSTS',
  RECEIVE_USER_NOTICES: 'RECEIVE_USER_NOTICES',
  ADD_USER_NOTICES: 'ADD_USER_NOTICES'
}

module.exports = actionTypes
